[tool.poetry]
name = "favie-data-schema"
version = "0.0.51-alpha.8"

description = "Favie Data Schema"
authors = ["allenz-srp <allenz@srp.one>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "2.6.4"
pydantic-settings = "2.2.1"
favie-common = {git = "https://github.com/SerendipityOneInc/favie-common.git", rev="0.1.5.alpha.2"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"