[tool.poetry]
name = "favie-data-schema"

<<<<<<< HEAD
version = "0.0.53-alpha.3"
=======
version = "0.0.53-alpha.6"
>>>>>>> e263236dffc4faa6df70266ca65b2b9f230bb8a3

description = "Favie Data Schema"
authors = ["allenz-srp <allenz@srp.one>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "2.6.4"
pydantic-settings = "2.2.1"
<<<<<<< HEAD
favie-common = {git = "https://github.com/SerendipityOneInc/favie-data-common.git", rev="0.0.1-alpha.0"}
=======
favie-common = {git = "https://github.com/SerendipityOneInc/favie-common.git", rev="0.1.5-alpha.4"}
>>>>>>> e263236dffc4faa6df70266ca65b2b9f230bb8a3

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"