name: Generate Pydantic Models from AVSC

on:
  push:
    branches:
      - '*'
    # paths:
    #   - '**/*.avsc'  # Run this workflow when .avsc files are changed

jobs:
  generate-pydantic-models:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install pydantic-avro
        run: pip install pydantic-avro jq
      
      - name: Generate Pydantic models
        run: make
      
      - name: Commit and Push Generated Models
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-generate Pydantic models from AVSC"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
