name: Generate Pydantic Models from AVSC

on:
  push:
    branches:
      - '*'
    # paths:
      # - '**/*.avsc'  # Run this workflow when .avsc files are changed

jobs:
  generate-pydantic-models:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install pydantic-avro
        run: pip install pydantic-avro jq poetry git+https://github.com/SerendipityOneInc/favie-common@0.1.5-alpha.2
      
      - name: Install dependencies
        run: |
          poetry update
      
      - name: Generate Pydantic models
        run: |
          for file in $(find avsc/crawl_data -name '*.avsc'); do
            model_name=$(basename "$file" .avsc)
            namespace_dir=$(jq -r '.namespace' "$file" | tr '.' '/')
            mkdir -p "$namespace_dir"
            pydantic-avro avro_to_pydantic --asvc "$file" --output "favie_data_schema/${namespace_dir}/${model_name}.py"
          done
      
      - name: Generate Product models
        run: |
          sh convert.sh
      
      - name: Commit and Push Generated Models
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-generate Pydantic models from AVSC"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
